# Example markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

MD013: false
  # # Number of characters
  # line_length: 140
  # # Number of characters for headings
  # heading_line_length: 50
  # # Number of characters for code blocks
  # code_block_line_length: 80
  # # Include code blocks
  # code_blocks: true
  # # Include tables
  # tables: true
  # # Include headings
  # headings: true
  # # Strict length checking
  # strict: false
  # # Stern length checking
  # stern: false
